"""add event outbox table for durable event publishing

Revision ID: 10c3eaf78508
Revises: 877c1c4434e7
Create Date: 2026-08-19 12:23:11.793152

Producer-side durability for domain events - see EventOutbox's own
docstring (app/events/models.py) for the full rationale. events.service.
publish_event_durably() writes here; flush_pending_outbox_events() drains
it to Kafka with retry. Wired into one representative money/entitlement-
critical call site (billing_service.change_plan) as of this migration -
same "representative, not universal" scoping as the original Kafka wiring.

NOTE ON SCOPE: autogenerate again detected the same 4 pre-existing,
unrelated supported_countries columns (activation_state/
activation_changed_at/activation_notes/activation_changed_by) flagged in
migration 4ec152435b05's docstring - still deliberately untouched here,
same reasoning as that migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10c3eaf78508'
down_revision: Union[str, None] = '877c1c4434e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_outbox_account_id'), 'event_outbox', ['account_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_created_at'), 'event_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_published_at'), 'event_outbox', ['published_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_topic'), 'event_outbox', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_outbox_topic'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_published_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_created_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_account_id'), table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###
