"""add fraud spam signal columns

Revision ID: 17826ded87fb
Revises: e660c33b001a
Create Date: 2026-08-04 21:01:27.677171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17826ded87fb'
down_revision: Union[str, None] = 'e660c33b001a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows as not-spam - required for a
    # NOT NULL column added to a table that may already have data.
    op.add_column(
        'call_records',
        sa.Column('is_suspected_spam', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'receptionist_calls',
        sa.Column('is_likely_spam', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('receptionist_calls', sa.Column('spam_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receptionist_calls', 'spam_reason')
    op.drop_column('receptionist_calls', 'is_likely_spam')
    op.drop_column('call_records', 'is_suspected_spam')
    # ### end Alembic commands ###
