"""add retention_policies table

Revision ID: 34860904d89a
Revises: 47516e4e72b1
Create Date: 2026-08-03 11:41:58.519923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34860904d89a'
down_revision: Union[str, None] = '47516e4e72b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_policies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('artifact_type', sa.Enum('VOICEMAIL', 'CALL_RECORDING', 'VIDEO_RECORDING', name='retention_artifact_type_enum'), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'artifact_type', name='uq_retention_account_artifact')
    )
    op.create_index(op.f('ix_retention_policies_account_id'), 'retention_policies', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_policies_account_id'), table_name='retention_policies')
    op.drop_table('retention_policies')
    # ### end Alembic commands ###
