"""add voicemails table

Revision ID: 3f94ba6bd0b7
Revises: 78df40955cea
Create Date: 2026-07-31 12:39:19.142989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f94ba6bd0b7'
down_revision: Union[str, None] = '78df40955cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voicemails',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_number_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voicemails_account_id'), 'voicemails', ['account_id'], unique=False)
    op.create_index(op.f('ix_voicemails_phone_number_id'), 'voicemails', ['phone_number_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voicemails_phone_number_id'), table_name='voicemails')
    op.drop_index(op.f('ix_voicemails_account_id'), table_name='voicemails')
    op.drop_table('voicemails')
    # ### end Alembic commands ###
