"""create compliance_rules and compliance_cases tables

Revision ID: 459db279e506
Revises: 1e90c4a197f1
Create Date: 2026-07-30 17:11:41.302998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459db279e506'
down_revision: Union[str, None] = '1e90c4a197f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_country'), 'compliance_rules', ['country'], unique=False)
    op.create_index(op.f('ix_compliance_rules_requirement_type'), 'compliance_rules', ['requirement_type'], unique=False)
    op.create_table('compliance_cases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('number_id', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=2), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='compliance_case_status_enum'), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_cases_account_id'), 'compliance_cases', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_cases_account_id'), table_name='compliance_cases')
    op.drop_table('compliance_cases')
    op.drop_index(op.f('ix_compliance_rules_requirement_type'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_country'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
