"""add video recording fields to video_sessions

Revision ID: 47516e4e72b1
Revises: 5d1653e7ffb3
Create Date: 2026-08-03 09:49:46.847543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47516e4e72b1'
down_revision: Union[str, None] = '5d1653e7ffb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_sessions', sa.Column('recording_egress_id', sa.String(length=100), nullable=True))
    op.add_column('video_sessions', sa.Column('recording_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_sessions', 'recording_url')
    op.drop_column('video_sessions', 'recording_egress_id')
    # ### end Alembic commands ###
