"""add zoikonex mock sync ledger and grace period

Revision ID: 482c3113664e
Revises: 36c375925c3a
Create Date: 2026-08-06 09:16:01.643766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '482c3113664e'
down_revision: Union[str, None] = '36c375925c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoikonex_sync_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.Enum('SUBSCRIPTION_SYNC', 'USAGE_SYNC', 'PAYMENT_EVENT_RECEIVED', name='zoikonex_sync_event_type_enum'), nullable=False),
    sa.Column('zoikonex_ref', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoikonex_sync_events_account_id'), 'zoikonex_sync_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_zoikonex_sync_events_created_at'), 'zoikonex_sync_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_zoikonex_sync_events_event_type'), 'zoikonex_sync_events', ['event_type'], unique=False)
    op.add_column('subscriptions', sa.Column('grace_period_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'grace_period_ends_at')
    op.drop_index(op.f('ix_zoikonex_sync_events_event_type'), table_name='zoikonex_sync_events')
    op.drop_index(op.f('ix_zoikonex_sync_events_created_at'), table_name='zoikonex_sync_events')
    op.drop_index(op.f('ix_zoikonex_sync_events_account_id'), table_name='zoikonex_sync_events')
    op.drop_table('zoikonex_sync_events')
    # ### end Alembic commands ###
