"""add confidential flag to video_sessions

Revision ID: 4a398a3d4ed6
Revises: 9d5f5c042e44
Create Date: 2026-08-05 17:11:11.061235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a398a3d4ed6'
down_revision: Union[str, None] = '9d5f5c042e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'video_sessions',
        sa.Column('confidential', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('video_sessions', 'confidential', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_sessions', 'confidential')
    # ### end Alembic commands ###
