"""add canonical template registry fields

Revision ID: 4b3c700763c1
Revises: 482c3113664e
Create Date: 2026-08-06 11:05:55.558846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3c700763c1'
down_revision: Union[str, None] = '482c3113664e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_templates', sa.Column('canonical_id', sa.String(length=30), nullable=True))
    op.add_column('notification_templates', sa.Column('domain', sa.String(length=20), nullable=True))
    op.add_column('notification_templates', sa.Column('spec_version', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_notification_templates_canonical_id'), 'notification_templates', ['canonical_id'], unique=True)
    op.create_index(op.f('ix_notification_templates_domain'), 'notification_templates', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_templates_domain'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_canonical_id'), table_name='notification_templates')
    op.drop_column('notification_templates', 'spec_version')
    op.drop_column('notification_templates', 'domain')
    op.drop_column('notification_templates', 'canonical_id')
    # ### end Alembic commands ###
