"""merged schema from anil and main branches

Revision ID: 52757c19af93
Revises: 
Create Date: 2026-08-01 10:51:44.324589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52757c19af93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('INDIVIDUAL', 'BUSINESS', name='account_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_target'), 'audit_events', ['target'], unique=False)
    op.create_table('compliance_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_country'), 'compliance_rules', ['country'], unique=False)
    op.create_index(op.f('ix_compliance_rules_requirement_type'), 'compliance_rules', ['requirement_type'], unique=False)
    op.create_table('platform_staff',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_staff_email'), 'platform_staff', ['email'], unique=True)
    op.create_table('compliance_cases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('number_id', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=2), nullable=False),
    sa.Column('requirement_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='compliance_case_status_enum'), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_cases_account_id'), 'compliance_cases', ['account_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consent_type', sa.Enum('AI_PROCESSING', name='consent_type_enum'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'consent_type', name='uq_consent_account_type')
    )
    op.create_index(op.f('ix_consent_records_account_id'), 'consent_records', ['account_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.Enum('VOICEMAIL', 'CALL', name='summary_source_type_enum'), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_account_id'), 'conversation_summaries', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_source_id'), 'conversation_summaries', ['source_id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('e164', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_sid', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('RESERVED', 'PURCHASE_PENDING', 'ACTIVE', 'SUSPENDED', 'CANCELLED', name='phone_number_status_enum'), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forwarding_number', sa.String(length=20), nullable=True),
    sa.Column('business_hours_start', sa.Time(), nullable=True),
    sa.Column('business_hours_end', sa.Time(), nullable=True),
    sa.Column('business_hours_timezone', sa.String(length=50), nullable=False),
    sa.Column('ai_receptionist_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_sid')
    )
    op.create_index(op.f('ix_phone_numbers_account_id'), 'phone_numbers', ['account_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_e164'), 'phone_numbers', ['e164'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='user_role_enum'), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('call_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('phone_number_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='call_direction_enum'), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('provider_call_sid', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_records_account_id'), 'call_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_call_records_phone_number_id'), 'call_records', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_call_records_provider_call_sid'), 'call_records', ['provider_call_sid'], unique=False)
    op.create_table('receptionist_calls',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_number_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('call_sid', sa.String(length=50), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=False),
    sa.Column('caller_name', sa.String(length=200), nullable=True),
    sa.Column('caller_company', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='receptionist_urgency_enum'), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receptionist_calls_account_id'), 'receptionist_calls', ['account_id'], unique=False)
    op.create_index(op.f('ix_receptionist_calls_call_sid'), 'receptionist_calls', ['call_sid'], unique=True)
    op.create_index(op.f('ix_receptionist_calls_phone_number_id'), 'receptionist_calls', ['phone_number_id'], unique=False)
    op.create_table('video_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('host_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'ENDED', name='video_session_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_sessions_account_id'), 'video_sessions', ['account_id'], unique=False)
    op.create_index(op.f('ix_video_sessions_host_user_id'), 'video_sessions', ['host_user_id'], unique=False)
    op.create_index(op.f('ix_video_sessions_room_name'), 'video_sessions', ['room_name'], unique=True)
    op.create_table('voicemails',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_number_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voicemails_account_id'), 'voicemails', ['account_id'], unique=False)
    op.create_index(op.f('ix_voicemails_phone_number_id'), 'voicemails', ['phone_number_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voicemails_phone_number_id'), table_name='voicemails')
    op.drop_index(op.f('ix_voicemails_account_id'), table_name='voicemails')
    op.drop_table('voicemails')
    op.drop_index(op.f('ix_video_sessions_room_name'), table_name='video_sessions')
    op.drop_index(op.f('ix_video_sessions_host_user_id'), table_name='video_sessions')
    op.drop_index(op.f('ix_video_sessions_account_id'), table_name='video_sessions')
    op.drop_table('video_sessions')
    op.drop_index(op.f('ix_receptionist_calls_phone_number_id'), table_name='receptionist_calls')
    op.drop_index(op.f('ix_receptionist_calls_call_sid'), table_name='receptionist_calls')
    op.drop_index(op.f('ix_receptionist_calls_account_id'), table_name='receptionist_calls')
    op.drop_table('receptionist_calls')
    op.drop_index(op.f('ix_call_records_provider_call_sid'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_phone_number_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_account_id'), table_name='call_records')
    op.drop_table('call_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_phone_numbers_e164'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_account_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_conversation_summaries_source_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_account_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_consent_records_account_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_compliance_cases_account_id'), table_name='compliance_cases')
    op.drop_table('compliance_cases')
    op.drop_index(op.f('ix_platform_staff_email'), table_name='platform_staff')
    op.drop_table('platform_staff')
    op.drop_index(op.f('ix_compliance_rules_requirement_type'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_country'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    op.drop_index(op.f('ix_audit_events_target'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
