"""add call quality telemetry to video participant sessions

Revision ID: 534b7aad220b
Revises: a2a6fcc3d704
Create Date: 2026-08-05 21:11:44.594973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534b7aad220b'
down_revision: Union[str, None] = 'a2a6fcc3d704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


connection_quality_enum = sa.Enum('EXCELLENT', 'GOOD', 'POOR', name='connection_quality_enum')


def upgrade() -> None:
    connection_quality_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'video_participant_sessions',
        sa.Column(
            'worst_connection_quality',
            sa.Enum('EXCELLENT', 'GOOD', 'POOR', name='connection_quality_enum', create_type=False),
            nullable=True,
        ),
    )
    op.add_column(
        'video_participant_sessions',
        sa.Column('reconnect_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('video_participant_sessions', 'reconnect_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_participant_sessions', 'reconnect_count')
    op.drop_column('video_participant_sessions', 'worst_connection_quality')
    # ### end Alembic commands ###
