"""add assigned_user_id to phone_numbers

Revision ID: 5540c51db816
Revises: 52757c19af93
Create Date: 2026-08-01 11:38:29.221326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5540c51db816'
down_revision: Union[str, None] = '52757c19af93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('assigned_user_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_phone_numbers_assigned_user_id'), 'phone_numbers', ['assigned_user_id'], unique=False)
    op.create_foreign_key(None, 'phone_numbers', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.drop_index(op.f('ix_phone_numbers_assigned_user_id'), table_name='phone_numbers')
    op.drop_column('phone_numbers', 'assigned_user_id')
    # ### end Alembic commands ###
