"""add recording_url to call_records

Revision ID: 5d1653e7ffb3
Revises: 5540c51db816
Create Date: 2026-08-01 12:36:17.849355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1653e7ffb3'
down_revision: Union[str, None] = '5540c51db816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('recording_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_records', 'recording_url')
    # ### end Alembic commands ###
