"""add zoikonex reconciliation runs and exceptions

Revision ID: 6f9bce3448b8
Revises: 6702184e75db
Create Date: 2026-08-10 12:28:00.908938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6f9bce3448b8'
down_revision: Union[str, None] = '6702184e75db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Note: autogenerate also picked up pre-existing, unrelated drift
    # (an 'agent_presence' unique-constraint name and 'calling_rates'
    # nullability/constraint-naming mismatch between the live DB and the
    # models) - deliberately left out of this migration since it's not
    # part of this change and hasn't been investigated; only the two new
    # reconciliation tables below are intentional.
    op.create_table('zoikonex_reconciliation_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('total_subscriptions', sa.Integer(), nullable=False),
    sa.Column('unsynced_subscriptions', sa.Integer(), nullable=False),
    sa.Column('total_usage_events', sa.Integer(), nullable=False),
    sa.Column('unsynced_usage_events', sa.Integer(), nullable=False),
    sa.Column('exceptions_found', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoikonex_reconciliation_runs_created_at'), 'zoikonex_reconciliation_runs', ['created_at'], unique=False)
    op.create_table('zoikonex_reconciliation_exceptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('exception_type', sa.Enum('SUBSCRIPTION_MISSING_ZOIKONEX_REF', 'USAGE_EVENT_MISSING_SYNC', name='zoikonex_reconciliation_exception_type_enum'), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolution_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['zoikonex_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoikonex_reconciliation_exceptions_account_id'), 'zoikonex_reconciliation_exceptions', ['account_id'], unique=False)
    op.create_index(op.f('ix_zoikonex_reconciliation_exceptions_created_at'), 'zoikonex_reconciliation_exceptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_zoikonex_reconciliation_exceptions_exception_type'), 'zoikonex_reconciliation_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_zoikonex_reconciliation_exceptions_resolved_at'), 'zoikonex_reconciliation_exceptions', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_zoikonex_reconciliation_exceptions_run_id'), 'zoikonex_reconciliation_exceptions', ['run_id'], unique=False)
    op.create_index(op.f('ix_zoikonex_reconciliation_exceptions_subject_id'), 'zoikonex_reconciliation_exceptions', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoikonex_reconciliation_exceptions_subject_id'), table_name='zoikonex_reconciliation_exceptions')
    op.drop_index(op.f('ix_zoikonex_reconciliation_exceptions_run_id'), table_name='zoikonex_reconciliation_exceptions')
    op.drop_index(op.f('ix_zoikonex_reconciliation_exceptions_resolved_at'), table_name='zoikonex_reconciliation_exceptions')
    op.drop_index(op.f('ix_zoikonex_reconciliation_exceptions_exception_type'), table_name='zoikonex_reconciliation_exceptions')
    op.drop_index(op.f('ix_zoikonex_reconciliation_exceptions_created_at'), table_name='zoikonex_reconciliation_exceptions')
    op.drop_index(op.f('ix_zoikonex_reconciliation_exceptions_account_id'), table_name='zoikonex_reconciliation_exceptions')
    op.drop_table('zoikonex_reconciliation_exceptions')
    op.drop_index(op.f('ix_zoikonex_reconciliation_runs_created_at'), table_name='zoikonex_reconciliation_runs')
    op.drop_table('zoikonex_reconciliation_runs')
    # ### end Alembic commands ###
