"""add video waiting guests table

Revision ID: 708c4caca189
Revises: 99397f3b7e8e
Create Date: 2026-08-05 14:59:53.065413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708c4caca189'
down_revision: Union[str, None] = '99397f3b7e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_waiting_guests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('video_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('guest_identity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ADMITTED', 'DENIED', name='video_waiting_guest_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_session_id'], ['video_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_identity')
    )
    op.create_index(op.f('ix_video_waiting_guests_video_session_id'), 'video_waiting_guests', ['video_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_waiting_guests_video_session_id'), table_name='video_waiting_guests')
    op.drop_table('video_waiting_guests')
    # ### end Alembic commands ###
