"""add ivr menu greeting and options

Revision ID: 75fa64bbaa08
Revises: e0b348bd8fe6
Create Date: 2026-08-06 17:17:32.922130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fa64bbaa08'
down_revision: Union[str, None] = 'e0b348bd8fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ivr_options',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_number_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('digit', sa.String(length=1), nullable=False),
    sa.Column('destination_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ivr_options_phone_number_id'), 'ivr_options', ['phone_number_id'], unique=False)
    op.add_column('phone_numbers', sa.Column('ivr_greeting', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'ivr_greeting')
    op.drop_index(op.f('ix_ivr_options_phone_number_id'), table_name='ivr_options')
    op.drop_table('ivr_options')
    # ### end Alembic commands ###
