"""add webhook endpoints and deliveries

Revision ID: 7656eb977026
Revises: 3d7e9a1b5c2f
Create Date: 2026-08-06 12:58:31.508185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7656eb977026'
down_revision: Union[str, None] = '3d7e9a1b5c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_account_id'), 'webhook_endpoints', ['account_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('endpoint_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DELIVERED', 'FAILED', name='webhook_delivery_status_enum'), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_event_type'), 'webhook_deliveries', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_event_type'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_webhook_endpoints_account_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    # ### end Alembic commands ###
