"""add receptionist_calls table and phone_numbers.ai_receptionist_enabled

Revision ID: 7671c3200961
Revises: a750b24c70e7
Create Date: 2026-07-31 18:27:34.356598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7671c3200961'
down_revision: Union[str, None] = 'a750b24c70e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receptionist_calls',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_number_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('call_sid', sa.String(length=50), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=False),
    sa.Column('caller_name', sa.String(length=200), nullable=True),
    sa.Column('caller_company', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='receptionist_urgency_enum'), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receptionist_calls_account_id'), 'receptionist_calls', ['account_id'], unique=False)
    op.create_index(op.f('ix_receptionist_calls_call_sid'), 'receptionist_calls', ['call_sid'], unique=True)
    op.create_index(op.f('ix_receptionist_calls_phone_number_id'), 'receptionist_calls', ['phone_number_id'], unique=False)
    op.add_column('phone_numbers', sa.Column('ai_receptionist_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'ai_receptionist_enabled')
    op.drop_index(op.f('ix_receptionist_calls_phone_number_id'), table_name='receptionist_calls')
    op.drop_index(op.f('ix_receptionist_calls_call_sid'), table_name='receptionist_calls')
    op.drop_index(op.f('ix_receptionist_calls_account_id'), table_name='receptionist_calls')
    op.drop_table('receptionist_calls')
    # ### end Alembic commands ###
