"""add call_records table

Revision ID: 78df40955cea
Revises: eaba39708baf
Create Date: 2026-07-31 12:13:27.547681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78df40955cea'
down_revision: Union[str, None] = 'eaba39708baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('phone_number_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='call_direction_enum'), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('provider_call_sid', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_records_account_id'), 'call_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_call_records_phone_number_id'), 'call_records', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_call_records_provider_call_sid'), 'call_records', ['provider_call_sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_records_provider_call_sid'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_phone_number_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_account_id'), table_name='call_records')
    op.drop_table('call_records')
    # ### end Alembic commands ###
