"""add structured ai fields to conversation_summaries

Revision ID: 82089d7b864c
Revises: bbc72bf994db
Create Date: 2026-08-03 13:42:33.889409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82089d7b864c'
down_revision: Union[str, None] = 'bbc72bf994db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_summaries', sa.Column('language', sa.String(length=10), nullable=True))
    # Postgres enum TYPE must exist before a column can reference it -
    # op.add_column alone doesn't create it for an existing table (same fix
    # as platform_staff_role_enum's migration).
    urgency_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='summary_urgency_enum')
    urgency_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('conversation_summaries', sa.Column('urgency', urgency_enum, nullable=True))
    op.add_column('conversation_summaries', sa.Column('action_items', sa.JSON(), nullable=True))
    op.add_column('conversation_summaries', sa.Column('suggested_follow_up', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_summaries', 'suggested_follow_up')
    op.drop_column('conversation_summaries', 'action_items')
    op.drop_column('conversation_summaries', 'urgency')
    sa.Enum(name='summary_urgency_enum').drop(op.get_bind(), checkfirst=True)
    op.drop_column('conversation_summaries', 'language')
    # ### end Alembic commands ###
