"""add mfa_secret and mfa_enabled to users

Revision ID: 887c66833bfd
Revises: 61af1135de3e
Create Date: 2026-07-31 15:59:29.550464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887c66833bfd'
down_revision: Union[str, None] = '61af1135de3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=64), nullable=True))
    # server_default backfills existing rows to False; dropped right after
    # so new rows rely on the ORM-level default instead of a DB default.
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'mfa_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    # ### end Alembic commands ###
