"""add consent_records table and conversation_summaries.model_version

Revision ID: 8d83d21c180d
Revises: ea26284f8c8d
Create Date: 2026-07-31 15:18:22.735126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d83d21c180d'
down_revision: Union[str, None] = 'ea26284f8c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consent_type', sa.Enum('AI_PROCESSING', name='consent_type_enum'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'consent_type', name='uq_consent_account_type')
    )
    op.create_index(op.f('ix_consent_records_account_id'), 'consent_records', ['account_id'], unique=False)
    op.add_column('conversation_summaries', sa.Column('model_version', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_summaries', 'model_version')
    op.drop_index(op.f('ix_consent_records_account_id'), table_name='consent_records')
    op.drop_table('consent_records')
    # ### end Alembic commands ###
