"""seed canonical email template estate - AUTH/NUM/PORT/COMP/VOICE/BILL

Revision ID: 8f2a1c9d4e6b
Revises: 4b3c700763c1
Create Date: 2026-08-06 12:00:00.000000

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2a1c9d4e6b'
down_revision: Union[str, None] = '4b3c700763c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Seeds the Email Communications System spec doc's full AUTH/NUM/PORT/COMP/
# VOICE/BILL template estate (100 of the doc's 234 total - the six domains
# tied to features that actually exist and fire real events today; the
# other 11 domains including the 39 internal-alert templates are deliberately
# not imported yet). Only ~27 of these 100 have a real call site wired up
# (see app/notifications/service.py's new notify_* functions) - the rest are
# seeded with their canonical copy so the registry matches the spec exactly,
# but aren't triggered by any code path yet. Upgrades 6 pre-existing rows
# (matched by key) to canonical copy instead of inserting duplicates.

_UPGRADE_KEYS = ['auth.password_reset', 'number.activated', 'porting.submitted', 'porting.approved', 'porting.completed', 'porting.rejected']


def upgrade() -> None:
    conn = op.get_bind()

    templates_table = sa.table(
        'notification_templates',
        sa.column('id', sa.String),
        sa.column('key', sa.String),
        sa.column('canonical_id', sa.String),
        sa.column('domain', sa.String),
        sa.column('spec_version', sa.String),
        sa.column('category', sa.String),
        sa.column('priority', sa.String),
        sa.column('subject_template', sa.String),
        sa.column('body_template', sa.Text),
    )
    op.bulk_insert(
        templates_table,
        [
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.verify_email_address',
            'canonical_id': 'ZLOC-EM-AUTH-001',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Verify your email for Zoiko Local',
            'body_template': 'Verify your email address\n\nHello {user_display_name}, confirm this email address for your Zoiko Local account. The link expires in {link_expiry_duration} and can be used once. Zoiko Local will never ask for your password, authentication code, or payment details by email.\n\nNext: Verify Email Address.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.verification_link_expired',
            'canonical_id': 'ZLOC-EM-AUTH-002',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local verification link expired',
            'body_template': 'Request a new verification link\n\nHello {user_display_name}, the verification link you opened has expired or has already been used. Request a new link to continue. Zoiko Local will never ask for your password, authentication code, or payment details by email.\n\nNext: Send a New Verification Link.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.account_activated',
            'canonical_id': 'ZLOC-EM-AUTH-003',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Welcome to Zoiko Local',
            'body_template': 'Your Zoiko Local account is ready\n\nHello {user_display_name}, your account is active. You can join your organization, claim assigned numbers, configure calling, connect approved devices, and review emergency-calling and privacy settings. Access depends on your organization’s plan and permissions.\n\nNext: Open Zoiko Local.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.sign_in_code',
            'canonical_id': 'ZLOC-EM-AUTH-004',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local sign-in code',
            'body_template': 'Complete your sign-in\n\nHello {user_display_name}, your one-time code is {security_one_time_code}. It expires in 10 minutes. Never share this code. Zoiko Local will never ask for your password, authentication code, or payment details by email.\n\nNext: Review Account Security.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.password_changed',
            'canonical_id': 'ZLOC-EM-AUTH-006',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local password was changed',
            'body_template': 'Password changed\n\nHello {user_display_name}, your password was changed on {security_activity_time}. If this was not you, begin account recovery and revoke unfamiliar sessions immediately. Zoiko Local will never ask for your password, authentication code, or payment details by email.\n\nNext: Secure My Account.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.new_sign_in_detected',
            'canonical_id': 'ZLOC-EM-AUTH-007',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'New sign-in to your Zoiko Local account',
            'body_template': 'We noticed a new sign-in\n\nHello {user_display_name}, your account was accessed on {security_activity_time} from {security_device} using {security_browser} near {security_approximate_location}. If you do not recognize it, revoke the session and secure your account. Zoiko Local will never ask for your password, authentication code, or payment details by email.\n\nNext: Review Sign-In Activity.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.suspicious_sign_in_blocked',
            'canonical_id': 'ZLOC-EM-AUTH-008',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'We blocked a suspicious Zoiko Local sign-in',
            'body_template': 'Suspicious access was blocked\n\nHello {user_display_name}, we blocked an unusual sign-in attempt on {security_activity_time} from {security_device} near {security_approximate_location}. If the attempt was yours, complete the identity check. Otherwise change your password and review sign-in methods.\n\nNext: Review Account Security.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.mfa_enabled',
            'canonical_id': 'ZLOC-EM-AUTH-009',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Multi-factor authentication is enabled',
            'body_template': 'Additional protection is active\n\nHello {user_display_name}, multi-factor authentication was enabled on {security_activity_time}. Store recovery codes securely and never share a verification code with anyone.\n\nNext: Review Security Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.mfa_disabled',
            'canonical_id': 'ZLOC-EM-AUTH-010',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Multi-factor authentication was disabled',
            'body_template': 'Additional protection was removed\n\nHello {user_display_name}, multi-factor authentication was disabled on {security_activity_time}. If you did not authorize this change, secure your account and revoke unfamiliar sessions immediately.\n\nNext: Secure My Account.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.recovery_code_used',
            'canonical_id': 'ZLOC-EM-AUTH-011',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'A recovery code was used for Zoiko Local',
            'body_template': 'Recovery access detected\n\nHello {user_display_name}, a recovery code was used on {security_activity_time} from {security_device}. If this was you, generate a replacement set. If it was not, secure your account immediately.\n\nNext: Review Recovery Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.account_temporarily_locked',
            'canonical_id': 'ZLOC-EM-AUTH-012',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local account was temporarily locked',
            'body_template': 'Account access is temporarily locked\n\nHello {user_display_name}, we temporarily locked your account after unusual or repeated access attempts. Your organization, numbers, call routing, and records remain protected. Complete the security review to restore access.\n\nNext: Restore Account Access.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.account_unlocked',
            'canonical_id': 'ZLOC-EM-AUTH-013',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Access to your Zoiko Local account was restored',
            'body_template': 'Your account is available again\n\nHello {user_display_name}, the security review is complete and account access has been restored. Review active sessions, passkeys, multi-factor authentication, and recovery methods before continuing.\n\nNext: Review Security Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.primary_email_change',
            'canonical_id': 'ZLOC-EM-AUTH-014',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'A change to your Zoiko Local email was requested',
            'body_template': 'Email-address change requested\n\nHello {user_display_name}, a request was made to change the primary email address for your account. If you initiated it, confirm the new address. If not, cancel the change from your current address and secure your account.\n\nNext: Review Email Change.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.passkey_added',
            'canonical_id': 'ZLOC-EM-AUTH-015',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'A passkey was added to your Zoiko Local account',
            'body_template': 'New passkey registered\n\nHello {user_display_name}, a passkey was added on {security_activity_time} from {security_device} near {security_approximate_location}. If you did not add it, remove it and secure your account immediately.\n\nNext: Review Sign-In Methods.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.passkey_removed',
            'canonical_id': 'ZLOC-EM-AUTH-016',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'A passkey was removed from your Zoiko Local account',
            'body_template': 'Passkey removed\n\nHello {user_display_name}, a passkey was removed on {security_activity_time}. If you did not remove it, another person may have access to your account. Secure it immediately.\n\nNext: Secure My Account.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.recovery_method_changed',
            'canonical_id': 'ZLOC-EM-AUTH-017',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local recovery settings changed',
            'body_template': 'Recovery settings updated\n\nHello {user_display_name}, a recovery method was {change_action} on {security_activity_time}. Method: {recovery_method_masked}. If you did not make this change, remove it and secure your account.\n\nNext: Review Recovery Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'auth.session_revoked',
            'canonical_id': 'ZLOC-EM-AUTH-018',
            'domain': 'AUTH',
            'spec_version': '1.0.0',
            'category': 'SECURITY',
            'priority': 'STANDARD',
            'subject_template': 'A Zoiko Local session was signed out',
            'body_template': 'Session access ended\n\nHello {user_display_name}, the session on {security_device} near {security_approximate_location} was signed out. Reason: {security_session_end_reason}. If you did not initiate this action, review account security.\n\nNext: Review Active Sessions.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_order_submitted',
            'canonical_id': 'ZLOC-EM-NUM-001',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'We received your Zoiko Local number order',
            'body_template': 'Number order submitted\n\nHello {user_display_name}, we received your request for {number_quantity} number(s) in {number_country_or_area}. Reference: {order_reference}. Availability, identity, address, intended-use, and regulatory checks may be required before assignment.\n\nNext: View Number Order.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_eligibility_information_required',
            'canonical_id': 'ZLOC-EM-NUM-002',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'More information is needed for your number request',
            'body_template': 'Number request needs information\n\nHello {user_display_name}, we need additional information to continue order {order_reference} for {number_country_or_area}. Required: {case_action_summary}. Do not send identity or address evidence by email.\n\nNext: Complete Number Requirements.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_order_approved',
            'canonical_id': 'ZLOC-EM-NUM-003',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local number order was approved',
            'body_template': 'Number order approved\n\nHello {user_display_name}, order {order_reference} was approved. Number: {number_masked_or_formatted}. Activation status: {number_activation_status}. Emergency-calling, outbound caller ID, and messaging capabilities remain subject to local availability and configuration.\n\nNext: Configure Number.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.order_not_approved',
            'canonical_id': 'ZLOC-EM-NUM-004',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Decision on your Zoiko Local number request',
            'body_template': 'Number request not approved\n\nHello {user_display_name}, we could not approve order {order_reference}. Reason category: {decision_reason_category}. Any payment authorization will be voided or adjusted according to its transaction status.\n\nNext: Review Decision.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_activation_delayed',
            'canonical_id': 'ZLOC-EM-NUM-006',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Activation of your Zoiko Local number is delayed',
            'body_template': 'Number activation delayed\n\nHello {user_display_name}, activation of {number_masked_or_formatted} has not completed as expected. Reference: {order_reference}. Current status: {number_activation_status}. Do not publish or rely on the number until activation is confirmed.\n\nNext: View Activation Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.assigned',
            'canonical_id': 'ZLOC-EM-NUM-007',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A Zoiko Local number was assigned to you',
            'body_template': 'Number assigned\n\nHello {user_display_name}, {number_formatted} was assigned to you in {organization_name}. Assignment: {number_assignment_type}. Review calling, messaging, voicemail, business hours, and emergency-location requirements.\n\nNext: Review Number Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.unassigned',
            'canonical_id': 'ZLOC-EM-NUM-008',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A Zoiko Local number assignment changed',
            'body_template': 'Number unassigned\n\nHello {user_display_name}, {number_formatted} was unassigned from {assignment_previous_target}. The number remains {number_lifecycle_status} and may route to {number_current_route_summary}.\n\nNext: Review Number Inventory.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_capability_changed',
            'canonical_id': 'ZLOC-EM-NUM-009',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Capabilities changed for {number_formatted}',
            'body_template': 'Number capabilities updated\n\nHello {user_display_name}, capabilities for {number_formatted} changed. Current capabilities: {number_capability_summary}. Do not advertise a capability until the Number Center confirms it is active.\n\nNext: Review Number Capabilities.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.verification_required',
            'canonical_id': 'ZLOC-EM-NUM-010',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Verification is required for your Zoiko Local number',
            'body_template': 'Number verification required\n\nHello {user_display_name}, continued use of {number_formatted} requires updated information. Required: {case_action_summary}. Service may be restricted or the number reclaimed if the requirement is not satisfied by the deadline.\n\nNext: Complete Number Verification.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_reservation_expiring',
            'canonical_id': 'ZLOC-EM-NUM-011',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local number reservation expires soon',
            'body_template': 'Number reservation expiring\n\nHello {user_display_name}, the reservation for {number_masked_or_formatted} expires on {number_reservation_expires_at}. Availability cannot be guaranteed after expiry.\n\nNext: Complete Number Order.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_release_requested',
            'canonical_id': 'ZLOC-EM-NUM-012',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Release requested for {number_formatted}',
            'body_template': 'Number release requested\n\nHello {user_display_name}, a request was made to release {number_formatted} on {release_effective_at}. Releasing a number may permanently end the right to use it. Verify porting, routing, published contact details, emergency services, and outstanding charges first.\n\nNext: Review Number Release.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_release_reminder',
            'canonical_id': 'ZLOC-EM-NUM-013',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': '{number_formatted} will be released soon',
            'body_template': 'Number release is approaching\n\nHello {user_display_name}, {number_formatted} is scheduled for release on {release_effective_at}. After release, Zoiko Local cannot guarantee recovery or reassignment of the number.\n\nNext: Keep This Number.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.released',
            'canonical_id': 'ZLOC-EM-NUM-014',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': '{number_formatted} was released from Zoiko Local',
            'body_template': 'Number released\n\nHello {user_display_name}, {number_formatted} was released on {release_completed_at}. Associated routing, caller ID, messaging, and emergency-location assignments were disabled. Retained records remain governed by policy and law.\n\nNext: View Number History.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'number.number_reclaimed_or_suspended_by_provider',
            'canonical_id': 'ZLOC-EM-NUM-015',
            'domain': 'NUM',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Urgent: service changed for a Zoiko Local number',
            'body_template': 'Number service restricted\n\nHello {user_display_name}, {number_formatted} was {number_enforcement_status} by the underlying provider or numbering authority. Reason category: {decision_reason_category}. Stop presenting the number as active and review remediation or replacement options.\n\nNext: Review Number Case.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_authorization_required',
            'canonical_id': 'ZLOC-EM-PORT-002',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Authorization is required to move your number',
            'body_template': 'Complete port authorization\n\nHello {user_display_name}, we need valid authorization for port request {port_reference}. Required document or action: {case_action_summary}. Names, addresses, account numbers, and signatures must match the losing provider’s records.\n\nNext: Complete Authorization.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_documents_received',
            'canonical_id': 'ZLOC-EM-PORT-003',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'We received your number-porting documents',
            'body_template': 'Port documents received\n\nHello {user_display_name}, documents for port request {port_reference} were received on {case_created_at}. We will validate them before submission to the carrier or portability system.\n\nNext: View Port Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_information_mismatch',
            'canonical_id': 'ZLOC-EM-PORT-004',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Information does not match for your port request',
            'body_template': 'Port request needs correction\n\nHello {user_display_name}, port request {port_reference} could not progress because {port_mismatch_summary}. Update the requested fields using the exact information held by the current provider.\n\nNext: Correct Port Information.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_date_proposed',
            'canonical_id': 'ZLOC-EM-PORT-006',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A porting date is proposed for your number',
            'body_template': 'Proposed porting date\n\nHello {user_display_name}, the proposed date for {number_masked_or_formatted} is {port_proposed_date} {port_timezone}. Keep existing service active, prepare routing and users in Zoiko Local, and avoid account changes with the losing provider.\n\nNext: Review Porting Date.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_date_confirmed',
            'canonical_id': 'ZLOC-EM-PORT-007',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your number port is confirmed for {port_confirmed_date}',
            'body_template': 'Porting date confirmed\n\nHello {user_display_name}, {number_masked_or_formatted} is confirmed to move to Zoiko Local on {port_confirmed_date} {port_timezone}. Configure inbound routes, outbound identity, emergency information, and fallback contacts before the change window.\n\nNext: Prepare for Porting.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_reminder',
            'canonical_id': 'ZLOC-EM-PORT-008',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Reminder: your number moves to Zoiko Local soon',
            'body_template': 'Your port is approaching\n\nHello {user_display_name}, {number_masked_or_formatted} is scheduled to port on {port_confirmed_date} {port_timezone}. Confirm users, routing, devices, internet connectivity, emergency settings, and support contacts.\n\nNext: Review Port Readiness.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_in_progress',
            'canonical_id': 'ZLOC-EM-PORT-009',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local number port is in progress',
            'body_template': 'Number port in progress\n\nHello {user_display_name}, the port of {number_masked_or_formatted} is now in progress. Avoid changing routing or resubmitting the request. Use the Porting Center for current status and escalation contacts.\n\nNext: View Live Port Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_partially_completed',
            'canonical_id': 'ZLOC-EM-PORT-011',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local port completed only in part',
            'body_template': 'Port partially completed\n\nHello {user_display_name}, port request {port_reference} is partially complete. Completed: {port_completed_summary}. Pending or failed: {port_pending_summary}. Use only the capabilities shown as active.\n\nNext: Review Port Details.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_delayed',
            'canonical_id': 'ZLOC-EM-PORT-012',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your number port has been delayed',
            'body_template': 'Porting delay\n\nHello {user_display_name}, port request {port_reference} will not complete as previously expected. Reason category: {decision_reason_category}. New estimate: {port_estimated_completion}. Existing service should remain active until completion is confirmed.\n\nNext: View Updated Port Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.canceled',
            'canonical_id': 'ZLOC-EM-PORT-014',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local port request was canceled',
            'body_template': 'Port request canceled\n\nHello {user_display_name}, port request {port_reference} was canceled on {port_canceled_at} by {port_canceled_by}. Current number provider and service remain unchanged unless separately confirmed.\n\nNext: View Port Record.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_out_authorization_requested',
            'canonical_id': 'ZLOC-EM-PORT-015',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A request was made to move a Zoiko Local number',
            'body_template': 'Port-out request received\n\nHello {user_display_name}, a port-out request was initiated for {number_masked_or_formatted} on {event_occurred_at}. If authorized, complete the secure process. If not, lock the request and review administrator access immediately.\n\nNext: Review Port-Out Request.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'porting.port_out_completed',
            'canonical_id': 'ZLOC-EM-PORT-016',
            'domain': 'PORT',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': '{number_formatted} moved away from Zoiko Local',
            'body_template': 'Port-out completed\n\nHello {user_display_name}, {number_formatted} completed port-out on {port_completed_at}. Zoiko Local routing, messaging, caller ID, and emergency assignments for the number are disabled. Review remaining services and charges.\n\nNext: Review Number Inventory.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.emergency_address_required',
            'canonical_id': 'ZLOC-EM-COMP-001',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Emergency address required for Zoiko Local calling',
            'body_template': 'Set your emergency address\n\nHello {user_display_name}, an emergency-service address is required for {number_masked_or_formatted} or {device_name}. Enter the physical location where the service is normally used. Do not use a mailing address unless it is also the caller’s service location.\n\nNext: Set Emergency Address.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.emergency_address_validated',
            'canonical_id': 'ZLOC-EM-COMP-002',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Your Zoiko Local emergency address was validated',
            'body_template': 'Emergency address confirmed\n\nHello {user_display_name}, the emergency address for {resource_summary} was validated: {emergency_address_summary}. Keep it current whenever the service location changes.\n\nNext: Review Emergency Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.emergency_address_rejected',
            'canonical_id': 'ZLOC-EM-COMP-003',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Your Zoiko Local emergency address needs correction',
            'body_template': 'Emergency address not validated\n\nHello {user_display_name}, we could not validate the emergency address for {resource_summary}. Reason: {emergency_validation_summary}. Correct it before relying on Zoiko Local for emergency calls.\n\nNext: Correct Emergency Address.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.emergency_calling_notice',
            'canonical_id': 'ZLOC-EM-COMP-004',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Important information about Zoiko Local emergency calling',
            'body_template': 'Emergency calling information\n\nHello {user_display_name}, emergency calling for {resource_summary} is {emergency_capability_status}. Internet, power, device, network, number, and registered-location conditions can affect connection and caller-location delivery. Keep an alternative way to contact emergency services.\n\nNext: Review Emergency Calling.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.emergency_calling_disabled_or_restricted',
            'canonical_id': 'ZLOC-EM-COMP-005',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Emergency calling is not available for a Zoiko Local service',
            'body_template': 'Emergency calling unavailable\n\nHello {user_display_name}, {resource_summary} cannot currently place supported emergency calls. Reason: {emergency_restriction_summary}. Use another available telephone service in an emergency and resolve the restriction before relying on Zoiko Local.\n\nNext: Review Restriction.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.emergency_call_follow_up',
            'canonical_id': 'ZLOC-EM-COMP-006',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'A Zoiko Local emergency call was placed',
            'body_template': 'Emergency-call record\n\nHello {user_display_name}, an emergency call was placed from {number_masked_or_formatted} on {call_started_at}. Registered location: {emergency_address_summary}. If the location was inaccurate, update it immediately. This notice does not reveal call content.\n\nNext: Review Emergency Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.caller_id_verification_required',
            'canonical_id': 'ZLOC-EM-COMP-007',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Verify an outbound caller ID for Zoiko Local',
            'body_template': 'Caller ID verification required\n\nHello {user_display_name}, {number_masked_or_formatted} cannot be used as outbound caller ID until ownership or authority is verified. Do not submit a number you do not control or have permission to present.\n\nNext: Verify Caller ID.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.caller_id_approved',
            'canonical_id': 'ZLOC-EM-COMP-008',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local caller ID was approved',
            'body_template': 'Caller ID approved\n\nHello {user_display_name}, {number_formatted} was approved as an outbound caller ID for {organization_name}. Approval does not guarantee display by every carrier or recipient device.\n\nNext: Configure Outbound Identity.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.caller_id_restricted_or_removed',
            'canonical_id': 'ZLOC-EM-COMP-009',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A Zoiko Local caller ID was restricted',
            'body_template': 'Outbound identity restricted\n\nHello {user_display_name}, {number_masked_or_formatted} can no longer be presented as configured. Reason category: {decision_reason_category}. Calls may use an alternate verified identity or be blocked.\n\nNext: Review Caller ID Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.call_recording_enabled',
            'canonical_id': 'ZLOC-EM-COMP-010',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Call recording was enabled in {organization_name}',
            'body_template': 'Call recording enabled\n\nHello {user_display_name}, call recording was enabled for {recording_scope_summary} effective {recording_effective_at}. Policy: {recording_policy_summary}. Users must follow applicable consent, disclosure, access, and retention requirements.\n\nNext: Review Recording Policy.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.call_recording_disabled',
            'canonical_id': 'ZLOC-EM-COMP-011',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Call recording was disabled in {organization_name}',
            'body_template': 'Call recording disabled\n\nHello {user_display_name}, recording for {recording_scope_summary} was disabled on {event_occurred_at}. New calls in that scope will not be recorded unless a separate policy applies.\n\nNext: Review Recording Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.recording_access_granted_or_revoked',
            'canonical_id': 'ZLOC-EM-COMP-012',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your access to Zoiko Local recordings changed',
            'body_template': 'Recording permissions updated\n\nHello {user_display_name}, your access to recordings in {organization_name} was {change_action}. Scope: {recording_scope_summary}. Downloading, sharing, transcription, and retention remain governed by policy.\n\nNext: Review Recording Access.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.consent_or_legal_basis_expiring',
            'canonical_id': 'ZLOC-EM-COMP-013',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'A Zoiko Local compliance record requires renewal',
            'body_template': 'Consent or authorization expiring\n\nHello {user_display_name}, the authorization supporting {case_scope_summary} expires on {case_review_deadline}. Renew it or stop the affected processing before expiry.\n\nNext: Review Compliance Record.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.regulatory_information_requested',
            'canonical_id': 'ZLOC-EM-COMP-014',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Regulatory information is required for Zoiko Local',
            'body_template': 'Compliance review requires action\n\nHello {user_display_name}, we need information for {case_scope_summary}. Reference: {case_reference}. Required: {case_action_summary}. Service may be limited while the review remains incomplete.\n\nNext: Complete Compliance Review.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'compliance.regulatory_restriction_applied_or_lifted',
            'canonical_id': 'ZLOC-EM-COMP-015',
            'domain': 'COMP',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'A compliance restriction changed your Zoiko Local service',
            'body_template': 'Service compliance status changed\n\nHello {user_display_name}, {case_scope_summary} is now {restriction_status} effective {restriction_start_at}. Reason: {decision_reason_category}. Follow the approved remediation or migration steps shown in the Compliance Center.\n\nNext: Review Compliance Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.calling_activated',
            'canonical_id': 'ZLOC-EM-VOICE-001',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Zoiko Local calling is active',
            'body_template': 'Calling is ready\n\nHello {user_display_name}, calling is now active for {scope_summary}. Confirm assigned numbers, outbound caller ID, routing, voicemail, emergency address, network quality, and device permissions before making production calls.\n\nNext: Open Calling Settings.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.calling_suspended',
            'canonical_id': 'ZLOC-EM-VOICE-002',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Zoiko Local calling was suspended',
            'body_template': 'Calling access restricted\n\nHello {user_display_name}, {call_capability_scope} calling for {scope_summary} was suspended effective {restriction_start_at}. Reason: {decision_reason_category}. Emergency-calling treatment is shown separately in the Emergency Services Center.\n\nNext: Review Calling Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.calling_restored',
            'canonical_id': 'ZLOC-EM-VOICE-003',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Zoiko Local calling was restored',
            'body_template': 'Calling is available again\n\nHello {user_display_name}, {call_capability_scope} calling for {scope_summary} was restored on {event_occurred_at}. Review routing and run a controlled test before normal use.\n\nNext: Test Calling.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.international_calling_enabled',
            'canonical_id': 'ZLOC-EM-VOICE-004',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'International calling was enabled',
            'body_template': 'International calling enabled\n\nHello {user_display_name}, international calling was enabled for {scope_summary}. Allowed destinations: {call_destination_summary}. Spending, time-of-day, user, and fraud controls remain active.\n\nNext: Review International Calling.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.international_calling_disabled',
            'canonical_id': 'ZLOC-EM-VOICE-005',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'International calling was disabled',
            'body_template': 'International calling restricted\n\nHello {user_display_name}, international calling for {scope_summary} was disabled on {event_occurred_at}. Reason: {decision_reason_category}. Domestic and emergency capabilities may differ.\n\nNext: Review Calling Permissions.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.high_risk_destination_blocked',
            'canonical_id': 'ZLOC-EM-VOICE-006',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'A Zoiko Local call was blocked',
            'body_template': 'Call blocked for protection\n\nHello {user_display_name}, a call from {call_source_masked} to {call_destination_masked} on {call_started_at} was blocked. Reason category: {decision_reason_category}. If the call was legitimate, request a controlled review; do not repeatedly retry.\n\nNext: Review Blocked Call.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.spend_threshold_reached',
            'canonical_id': 'ZLOC-EM-VOICE-007',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Zoiko Local calling reached a spending threshold',
            'body_template': 'Calling spend alert\n\nHello {user_display_name}, {organization_name} reached {usage_threshold_percentage}% of its {usage_period_label} calling limit. Current usage: {usage_amount} {usage_currency}. Threshold alerts do not guarantee that further charges are blocked.\n\nNext: Review Usage.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.call_quality_issue_detected',
            'canonical_id': 'ZLOC-EM-VOICE-008',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Zoiko Local detected a call-quality issue',
            'body_template': 'Call quality needs attention\n\nHello {user_display_name}, quality for {scope_summary} was degraded during {quality_window}. Indicators: {quality_summary}. Review network conditions, device configuration, and the service-status page before escalating.\n\nNext: Review Call Quality.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.missed_call',
            'canonical_id': 'ZLOC-EM-VOICE-009',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'You missed a Zoiko Local call',
            'body_template': 'Missed call\n\nHello {user_display_name}, you missed a call from {call_caller_display_safe} to {number_masked_or_formatted} at {call_started_local}. Caller identity may be unavailable, altered, or unverified.\n\nNext: Open Call Activity.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.call_summary_available',
            'canonical_id': 'ZLOC-EM-VOICE-010',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A Zoiko Local call summary is available',
            'body_template': 'Call summary ready\n\nHello {user_display_name}, an authorized summary is available for the call at {call_started_local} involving {call_counterparty_safe}. Email contains no call content, recording, or transcript.\n\nNext: View Call Summary.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.voicemail_received',
            'canonical_id': 'ZLOC-EM-VOICE-011',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'New voicemail in Zoiko Local',
            'body_template': 'You have a new voicemail\n\nHello {user_display_name}, a voicemail was received for {number_masked_or_formatted} at {voicemail_received_local} from {call_caller_display_safe}. Duration: {voicemail_duration}. The recording and transcript are not included in email.\n\nNext: Open Voicemail.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.voicemail_transcription_ready',
            'canonical_id': 'ZLOC-EM-VOICE-012',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local voicemail transcription is ready',
            'body_template': 'Voicemail transcription ready\n\nHello {user_display_name}, transcription completed for the voicemail received at {voicemail_received_local}. Automated transcription may contain errors and must not be treated as an authoritative record.\n\nNext: Review Transcription.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.scheduled_call_reminder',
            'canonical_id': 'ZLOC-EM-VOICE-013',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Reminder: {call_title} starts soon',
            'body_template': 'Scheduled call reminder\n\nHello {user_display_name}, {call_title} starts at {call_start_local} {call_timezone}. Participants: {call_participant_summary}. Join access is revalidated when opened.\n\nNext: Join Scheduled Call.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'voice.scheduled_call_changed_or_canceled',
            'canonical_id': 'ZLOC-EM-VOICE-014',
            'domain': 'VOICE',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A scheduled Zoiko Local call changed',
            'body_template': 'Scheduled call updated\n\nHello {user_display_name}, {call_title} was {call_change_type}. Previous time: {call_previous_start_local}. Current time: {call_start_local} {call_timezone}. Reason or note: {call_change_summary}.\n\nNext: Review Scheduled Call.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.plan_started',
            'canonical_id': 'ZLOC-EM-BILL-001',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local plan is active',
            'body_template': 'Plan activated\n\nHello {user_display_name}, {organization_name} is now on {subscription_plan_name}. Billing interval: {subscription_billing_interval}. Next billing date: {subscription_next_billing_date}. Included users, numbers, usage, and features are shown in Billing.\n\nNext: Review Plan.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.trial_started',
            'canonical_id': 'ZLOC-EM-BILL-002',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local trial has started',
            'body_template': 'Trial active\n\nHello {user_display_name}, the {subscription_plan_name} trial for {organization_name} ends on {subscription_trial_end_date}. After the trial: {subscription_post_trial_terms}. We will provide any notice required by the applicable legal rules before a charge.\n\nNext: Explore Zoiko Local.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.trial_ending',
            'canonical_id': 'ZLOC-EM-BILL-003',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local trial ends on {subscription_trial_end_date}',
            'body_template': 'Trial ending soon\n\nHello {user_display_name}, {organization_name} will {subscription_end_behavior} when the trial ends. Amount if converted: {subscription_price} {subscription_currency} per {subscription_billing_interval}. Payment method: {transaction_payment_method_masked}.\n\nNext: Review Trial.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.renewal_reminder',
            'canonical_id': 'ZLOC-EM-BILL-004',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local plan renews on {subscription_next_billing_date}',
            'body_template': 'Plan renewal approaching\n\nHello {user_display_name}, {subscription_plan_name} renews on {subscription_next_billing_date} for {subscription_price} {subscription_currency}. Payment method: {transaction_payment_method_masked}. Cancel or change the plan before renewal to avoid the next charge where permitted.\n\nNext: Review Subscription.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.plan_price_change',
            'canonical_id': 'ZLOC-EM-BILL-005',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A price change to your Zoiko Local plan',
            'body_template': 'Your plan price is changing\n\nHello {user_display_name}, the price of {subscription_plan_name} changes from {pricing_current_price} to {pricing_new_price} {subscription_currency} effective {pricing_effective_date}. Your options and any consent requirement depend on the applicable terms and jurisdiction.\n\nNext: Review My Options.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.plan_changed',
            'canonical_id': 'ZLOC-EM-BILL-006',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local plan changed',
            'body_template': 'Plan updated\n\nHello {user_display_name}, {organization_name} changed from {subscription_previous_plan} to {subscription_plan_name} effective {subscription_effective_at}. Proration or credit: {transaction_adjustment_summary}. Review users, numbers, included usage, retention, and feature limits.\n\nNext: Review Plan Change.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.cancellation_confirmed',
            'canonical_id': 'ZLOC-EM-BILL-007',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local cancellation is confirmed',
            'body_template': 'Cancellation confirmed\n\nHello {user_display_name}, {subscription_plan_name} will not renew. Service remains active until {subscription_period_end_date}. Numbers, porting, recordings, messages, and data exports may require action before the end date.\n\nNext: Review Cancellation.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.subscription_ended',
            'canonical_id': 'ZLOC-EM-BILL-008',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local subscription ended',
            'body_template': 'Subscription ended\n\nHello {user_display_name}, {subscription_plan_name} ended on {subscription_ended_date}. Current service state: {subscription_post_end_status}. Number retention, porting, release, data access, and outstanding charges follow their separate governed workflows.\n\nNext: Review Account Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.payment_method_added_or_changed',
            'canonical_id': 'ZLOC-EM-BILL-009',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Zoiko Local payment settings changed',
            'body_template': 'Payment method updated\n\nHello {user_display_name}, a payment method for {organization_name} was {change_action} on {security_activity_time}. Method: {transaction_payment_method_masked}. If unauthorized, secure the organization and contact Billing.\n\nNext: Review Billing Security.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.payment_succeeded',
            'canonical_id': 'ZLOC-EM-BILL-010',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Zoiko Local payment received',
            'body_template': 'Payment successful\n\nHello {user_display_name}, we received {transaction_total} {transaction_currency} for {transaction_description} on {transaction_date}. Payment method: {transaction_payment_method_masked}.\n\nNext: View Receipt.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.payment_failed',
            'canonical_id': 'ZLOC-EM-BILL-011',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Payment failed for your Zoiko Local services',
            'body_template': 'We could not process the payment\n\nHello {user_display_name}, payment of {transaction_total} {transaction_currency} for {transaction_description} failed. Reason category: {transaction_failure_category}. The grace period and affected services are shown in Billing.\n\nNext: Resolve Payment Issue.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.payment_reminder',
            'canonical_id': 'ZLOC-EM-BILL-012',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Payment is still required for Zoiko Local',
            'body_template': 'Payment remains outstanding\n\nHello {user_display_name}, {transaction_total} {transaction_currency} remains due for {transaction_description}. Service-impact date: {dunning_suspension_date}. Expected consequence: {dunning_consequence_summary}.\n\nNext: Resolve Payment Issue.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.final_payment_notice',
            'canonical_id': 'ZLOC-EM-BILL-013',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Final notice: payment required for Zoiko Local',
            'body_template': 'Action needed to keep services active\n\nHello {user_display_name}, we still cannot process {transaction_total} {transaction_currency} for {transaction_description}. On {dunning_suspension_date}, {dunning_consequence_summary}. If payment has been resolved, no further action is needed.\n\nNext: Resolve Payment Issue.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.service_suspended_for_nonpayment',
            'canonical_id': 'ZLOC-EM-BILL-014',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Zoiko Local services were restricted for nonpayment',
            'body_template': 'Billing restriction applied\n\nHello {user_display_name}, {scope_summary} was restricted on {restriction_start_at} because payment remains outstanding. Affected services: {restriction_affected_services}. Emergency-calling treatment and number-retention status are displayed separately.\n\nNext: Restore Services.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.service_restored',
            'canonical_id': 'ZLOC-EM-BILL-015',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'CRITICAL',
            'subject_template': 'Zoiko Local services were restored',
            'body_template': 'Services restored\n\nHello {user_display_name}, payment was resolved and {scope_summary} was restored on {event_occurred_at}. Run controlled tests for inbound calls, outbound calls, messages, routes, and devices.\n\nNext: Review Service Status.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.invoice_available',
            'canonical_id': 'ZLOC-EM-BILL-016',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local invoice is ready',
            'body_template': 'Invoice available\n\nHello {user_display_name}, invoice {transaction_reference} for {billing_period} is ready. Subtotal: {transaction_subtotal} {transaction_currency}. Tax: {transaction_tax}. Total: {transaction_total}. Retrieve the document from Billing.\n\nNext: View Invoice.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.usage_threshold_alert',
            'canonical_id': 'ZLOC-EM-BILL-017',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Zoiko Local usage reached a threshold',
            'body_template': 'Usage alert\n\nHello {user_display_name}, {usage_metric_name} reached {usage_threshold_percentage}% of the configured threshold for {billing_period}. Current: {usage_current}. Included: {usage_included}. Additional-use terms: {usage_overage_summary}.\n\nNext: Review Usage.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.credit_or_refund_processed',
            'canonical_id': 'ZLOC-EM-BILL-018',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'A Zoiko Local refund or credit was processed',
            'body_template': 'Billing adjustment completed\n\nHello {user_display_name}, a {transaction_adjustment_type} of {transaction_adjustment_amount} {transaction_currency} was processed for reference {transaction_reference}. Reason: {transaction_adjustment_reason}.\n\nNext: View Billing Activity.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.tax_information_required',
            'canonical_id': 'ZLOC-EM-BILL-019',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Tax information is required for Zoiko Local',
            'body_template': 'Billing information required\n\nHello {user_display_name}, we need updated tax or invoicing information for {organization_name} before {case_review_deadline}. Required: {case_action_summary}. Do not send tax identifiers by email.\n\nNext: Update Tax Information.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.credit_balance_or_deposit_alert',
            'canonical_id': 'ZLOC-EM-BILL-020',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Your Zoiko Local balance is running low',
            'body_template': 'Balance alert\n\nHello {user_display_name}, the available balance for {billing_balance_scope} is {billing_balance} {billing_currency}, below the threshold of {billing_threshold}. Expected impact: {billing_consequence_summary}.\n\nNext: Review Balance.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.billing_contact_changed',
            'canonical_id': 'ZLOC-EM-BILL-021',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Zoiko Local billing contacts changed',
            'body_template': 'Billing contact updated\n\nHello {user_display_name}, billing contacts for {organization_name} changed on {event_occurred_at}. Added: {billing_contacts_added}. Removed: {billing_contacts_removed}.\n\nNext: Review Billing Contacts.',
        },
        {
            'id': str(uuid.uuid4()),
            'key': 'billing.billing_dispute_opened_or_resolved',
            'canonical_id': 'ZLOC-EM-BILL-022',
            'domain': 'BILL',
            'spec_version': '1.0.0',
            'category': 'TRANSACTIONAL',
            'priority': 'STANDARD',
            'subject_template': 'Update on Zoiko Local billing case {case_reference}',
            'body_template': 'Billing case updated\n\nHello {user_display_name}, billing case {case_reference} is {case_status}. Transaction: {transaction_reference}. Required action or outcome: {case_action_summary}. Submit evidence only through the secure case portal.\n\nNext: View Billing Case.',
        },
        ],
    )

    conn.execute(
        sa.text(
            "UPDATE notification_templates SET canonical_id=:cid, domain=:dom, spec_version=:ver, "
            "category=:cat, priority=:pri, subject_template=:subj, body_template=:body "
            "WHERE key=:key"
        ).bindparams(
            cid='ZLOC-EM-AUTH-005', dom='AUTH', ver='1.0.0',
            cat='SECURITY', pri='STANDARD',
            subj='Reset your Zoiko Local password', body='Reset your password\n\nHello {user_display_name}, we received a request to reset your password. The link is single-use and expires in 30 minutes. If you did not request this, do not use the link and review active sessions. Zoiko Local will never ask for your password, authentication code, or payment details by email.\n\nNext: Reset Password.\n\n{reset_url}',
            key='auth.password_reset',
        )
    )
    conn.execute(
        sa.text(
            "UPDATE notification_templates SET canonical_id=:cid, domain=:dom, spec_version=:ver, "
            "category=:cat, priority=:pri, subject_template=:subj, body_template=:body "
            "WHERE key=:key"
        ).bindparams(
            cid='ZLOC-EM-NUM-005', dom='NUM', ver='1.0.0',
            cat='TRANSACTIONAL', pri='STANDARD',
            subj='{number_formatted} is active on Zoiko Local', body='Your number is active\n\nHello {user_display_name}, {number_formatted} is now active for {organization_name}. Confirm its inbound route, outbound caller ID rules, emergency address where applicable, voicemail, hours, and failover destination.\n\nNext: Configure Active Number.',
            key='number.activated',
        )
    )
    conn.execute(
        sa.text(
            "UPDATE notification_templates SET canonical_id=:cid, domain=:dom, spec_version=:ver, "
            "category=:cat, priority=:pri, subject_template=:subj, body_template=:body "
            "WHERE key=:key"
        ).bindparams(
            cid='ZLOC-EM-PORT-001', dom='PORT', ver='1.0.0',
            cat='TRANSACTIONAL', pri='STANDARD',
            subj='Your Zoiko Local port request was started', body='Move your number to Zoiko Local\n\nHello {user_display_name}, port request {port_reference} was created for {number_masked_or_formatted}. Service with the current provider must remain active until completion. Do not cancel the existing service unless the Porting Center instructs you to do so.\n\nNext: Continue Port Request.',
            key='porting.submitted',
        )
    )
    conn.execute(
        sa.text(
            "UPDATE notification_templates SET canonical_id=:cid, domain=:dom, spec_version=:ver, "
            "category=:cat, priority=:pri, subject_template=:subj, body_template=:body "
            "WHERE key=:key"
        ).bindparams(
            cid='ZLOC-EM-PORT-005', dom='PORT', ver='1.0.0',
            cat='TRANSACTIONAL', pri='STANDARD',
            subj='Your number port was submitted', body='Port submitted\n\nHello {user_display_name}, port request {port_reference} for {number_masked_or_formatted} was submitted on {port_submitted_at}. Current estimated completion: {port_estimated_completion}. Estimates may change until a firm date is confirmed.\n\nNext: Track Port Request.',
            key='porting.approved',
        )
    )
    conn.execute(
        sa.text(
            "UPDATE notification_templates SET canonical_id=:cid, domain=:dom, spec_version=:ver, "
            "category=:cat, priority=:pri, subject_template=:subj, body_template=:body "
            "WHERE key=:key"
        ).bindparams(
            cid='ZLOC-EM-PORT-010', dom='PORT', ver='1.0.0',
            cat='TRANSACTIONAL', pri='STANDARD',
            subj='{number_formatted} has moved to Zoiko Local', body='Number port completed\n\nHello {user_display_name}, port request {port_reference} completed on {port_completed_at}. Test inbound calls, outbound caller ID, messages where supported, voicemail, emergency calling, and failover routing. Do not cancel other linked services until independently confirmed.\n\nNext: Run Post-Port Checks.',
            key='porting.completed',
        )
    )
    conn.execute(
        sa.text(
            "UPDATE notification_templates SET canonical_id=:cid, domain=:dom, spec_version=:ver, "
            "category=:cat, priority=:pri, subject_template=:subj, body_template=:body "
            "WHERE key=:key"
        ).bindparams(
            cid='ZLOC-EM-PORT-013', dom='PORT', ver='1.0.0',
            cat='TRANSACTIONAL', pri='CRITICAL',
            subj='Your Zoiko Local port request was rejected', body='Port request rejected\n\nHello {user_display_name}, port request {port_reference} was rejected. Reason: {port_rejection_summary}. The number remains with the current provider. Correct and resubmit only after validating the required information.\n\nNext: Resolve Port Rejection.',
            key='porting.rejected',
        )
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "UPDATE notification_templates SET canonical_id=NULL, domain=NULL, spec_version=NULL "
            "WHERE key = ANY(:keys)"
        ).bindparams(keys=list(_UPGRADE_KEYS))
    )
    op.execute(
        sa.text(
            "DELETE FROM notification_templates WHERE domain IN "
            "('AUTH', 'NUM', 'PORT', 'COMP', 'VOICE', 'BILL') AND key != ALL(:keys)"
        ).bindparams(keys=list(_UPGRADE_KEYS))
    )
