"""add error_events table

Revision ID: 99397f3b7e8e
Revises: 17826ded87fb
Create Date: 2026-08-05 09:52:49.126013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99397f3b7e8e'
down_revision: Union[str, None] = '17826ded87fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('exception_type', sa.String(length=200), nullable=True),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_events_account_id'), 'error_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_error_events_exception_type'), 'error_events', ['exception_type'], unique=False)
    op.create_index(op.f('ix_error_events_path'), 'error_events', ['path'], unique=False)
    op.create_index(op.f('ix_error_events_request_id'), 'error_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_error_events_status_code'), 'error_events', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_events_status_code'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_request_id'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_path'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_exception_type'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_account_id'), table_name='error_events')
    op.drop_table('error_events')
    # ### end Alembic commands ###
