"""add role to platform_staff

Revision ID: 9c044a2f0335
Revises: 47516e4e72b1
Create Date: 2026-08-03 11:54:01.851948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c044a2f0335'
down_revision: Union[str, None] = '47516e4e72b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    # server_default backfills any pre-existing staff row (e.g. the seeded
    # ops account) as super_admin, preserving its current full access rather
    # than silently locking it out - new rows must still pass role
    # explicitly (see staff.service.create_staff), so the default is dropped
    # right after the backfill instead of staying in place indefinitely.
    role_enum = sa.Enum('SUPPORT', 'COMPLIANCE_OFFICER', 'SUPER_ADMIN', name='platform_staff_role_enum')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'platform_staff',
        # server_default uses the enum MEMBER NAME ('SUPER_ADMIN'), not its
        # .value ('super_admin') - SQLAlchemy's Enum(PythonEnumClass, ...)
        # stores/matches on .name by default (same convention as
        # user_role_enum/account_type_enum elsewhere in this schema).
        sa.Column('role', role_enum, nullable=False, server_default='SUPER_ADMIN'),
    )
    op.alter_column('platform_staff', 'role', server_default=None)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('platform_staff', 'role')
    sa.Enum(name='platform_staff_role_enum').drop(op.get_bind(), checkfirst=True)
    op.alter_column('audit_events', 'action',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
