"""notification priority tiers and quiet hours preferences

Revision ID: a2a6fcc3d704
Revises: 4a398a3d4ed6
Create Date: 2026-08-05 20:08:13.289259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a6fcc3d704'
down_revision: Union[str, None] = '4a398a3d4ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


notification_priority_enum = sa.Enum('CRITICAL', 'STANDARD', name='notification_priority_enum')


def upgrade() -> None:
    notification_priority_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('transactional_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('quiet_hours_timezone', sa.String(length=64), nullable=False, server_default='UTC'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.add_column(
        'notification_templates',
        sa.Column(
            'priority',
            sa.Enum('CRITICAL', 'STANDARD', name='notification_priority_enum', create_type=False),
            nullable=False,
            server_default='STANDARD',
        ),
    )
    op.alter_column('notification_templates', 'priority', server_default=None)

    # SECURITY-category / access-critical events get CRITICAL priority so
    # they always send, ignoring quiet hours and the transactional opt-out.
    op.execute(
        "UPDATE notification_templates SET priority = 'CRITICAL' "
        "WHERE key IN ('number.suspended', 'team_member.added')"
    )

    # Postgres can't add an enum value inside the same transaction it's used
    # in below, but this migration only adds the value - nothing in this
    # same upgrade() references 'SUPPRESSED' yet, so no separate transaction
    # is needed (same pattern as e660c33b001a_add_viewer_role.py).
    op.execute("ALTER TYPE notification_delivery_status_enum ADD VALUE IF NOT EXISTS 'SUPPRESSED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_templates', 'priority')
    op.drop_table('notification_preferences')
    # Postgres can't drop a single enum value without recreating the whole
    # type - not worth it for a downgrade path (same rationale as every
    # other enum-add migration in this chain).
    # ### end Alembic commands ###
