"""add forwarding and business hours fields to phone_numbers

Revision ID: a750b24c70e7
Revises: 8d83d21c180d
Create Date: 2026-07-31 17:35:30.897788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a750b24c70e7'
down_revision: Union[str, None] = '8d83d21c180d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('forwarding_number', sa.String(length=20), nullable=True))
    op.add_column('phone_numbers', sa.Column('business_hours_start', sa.Time(), nullable=True))
    op.add_column('phone_numbers', sa.Column('business_hours_end', sa.Time(), nullable=True))
    op.add_column('phone_numbers', sa.Column('business_hours_timezone', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'business_hours_timezone')
    op.drop_column('phone_numbers', 'business_hours_end')
    op.drop_column('phone_numbers', 'business_hours_start')
    op.drop_column('phone_numbers', 'forwarding_number')
    # ### end Alembic commands ###
