"""add ring group destinations

Revision ID: b292ad2dad84
Revises: 6b2c75e364cb
Create Date: 2026-08-06 14:16:48.481437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b292ad2dad84'
down_revision: Union[str, None] = '6b2c75e364cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ring_group_destinations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_number_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('destination_number', sa.String(length=20), nullable=False),
    sa.Column('ring_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ring_group_destinations_phone_number_id'), 'ring_group_destinations', ['phone_number_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ring_group_destinations_phone_number_id'), table_name='ring_group_destinations')
    op.drop_table('ring_group_destinations')
    # ### end Alembic commands ###
