"""add escalation_user_id to phone_numbers

Revision ID: bbc72bf994db
Revises: 9c044a2f0335
Create Date: 2026-08-03 12:51:55.836459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc72bf994db'
down_revision: Union[str, None] = '9c044a2f0335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('escalation_user_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'phone_numbers', 'users', ['escalation_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.drop_column('phone_numbers', 'escalation_user_id')
    # ### end Alembic commands ###
