"""add provider call traces for distributed tracing

Revision ID: cb697a7130bc
Revises: 534b7aad220b
Create Date: 2026-08-05 22:36:44.178337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb697a7130bc'
down_revision: Union[str, None] = '534b7aad220b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_call_traces',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_call_traces_created_at'), 'provider_call_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_call_traces_operation'), 'provider_call_traces', ['operation'], unique=False)
    op.create_index(op.f('ix_provider_call_traces_provider'), 'provider_call_traces', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_call_traces_request_id'), 'provider_call_traces', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_call_traces_request_id'), table_name='provider_call_traces')
    op.drop_index(op.f('ix_provider_call_traces_provider'), table_name='provider_call_traces')
    op.drop_index(op.f('ix_provider_call_traces_operation'), table_name='provider_call_traces')
    op.drop_index(op.f('ix_provider_call_traces_created_at'), table_name='provider_call_traces')
    op.drop_table('provider_call_traces')
    # ### end Alembic commands ###
