"""add plans and subscriptions for entitlement gating

Revision ID: cdc47723ab0f
Revises: cb697a7130bc
Create Date: 2026-08-05 23:07:18.696175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc47723ab0f'
down_revision: Union[str, None] = 'cb697a7130bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Deliberately no price fields here - see Plan's docstring. Limits are a
# reasonable Phase-1 starting point, not a commercial decision locked in
# stone; they're stored as data specifically so they can be tuned later
# without a code change.
_PLANS = [
    {
        # Generous on purpose - a 14-day trial should let a business fully
        # evaluate multi-user/multi-number features (team routing, several
        # numbers), not bump into limits while still deciding whether to buy.
        "plan_code": "free_trial", "name": "Free Trial",
        "max_numbers": 3, "max_team_seats": 5,
        "monthly_voice_minutes": 500, "monthly_video_minutes": 300, "monthly_ai_summaries": 100,
        "trial_days": 14, "sort_order": 0,
    },
    {
        "plan_code": "starter", "name": "Starter",
        "max_numbers": 3, "max_team_seats": 5,
        "monthly_voice_minutes": 1000, "monthly_video_minutes": 500, "monthly_ai_summaries": 200,
        "trial_days": 0, "sort_order": 1,
    },
    {
        "plan_code": "business", "name": "Business",
        "max_numbers": 10, "max_team_seats": 20,
        "monthly_voice_minutes": 5000, "monthly_video_minutes": 2500, "monthly_ai_summaries": 1000,
        "trial_days": 0, "sort_order": 2,
    },
    {
        "plan_code": "enterprise", "name": "Enterprise",
        "max_numbers": 1000, "max_team_seats": 1000,
        "monthly_voice_minutes": 1000000, "monthly_video_minutes": 1000000, "monthly_ai_summaries": 1000000,
        "trial_days": 0, "sort_order": 3,
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_numbers', sa.Integer(), nullable=False),
    sa.Column('max_team_seats', sa.Integer(), nullable=False),
    sa.Column('monthly_voice_minutes', sa.Integer(), nullable=False),
    sa.Column('monthly_video_minutes', sa.Integer(), nullable=False),
    sa.Column('monthly_ai_summaries', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('plan_code')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', name='subscription_status_enum'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zoikonex_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.plan_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_account_id'), 'subscriptions', ['account_id'], unique=True)
    # ### end Alembic commands ###

    plans_table = sa.table(
        'plans',
        sa.column('plan_code', sa.String),
        sa.column('name', sa.String),
        sa.column('max_numbers', sa.Integer),
        sa.column('max_team_seats', sa.Integer),
        sa.column('monthly_voice_minutes', sa.Integer),
        sa.column('monthly_video_minutes', sa.Integer),
        sa.column('monthly_ai_summaries', sa.Integer),
        sa.column('trial_days', sa.Integer),
        sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(plans_table, _PLANS)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_account_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('plans')
    # ### end Alembic commands ###
