"""add video_participant_sessions table

Revision ID: de176a4fd695
Revises: e15d74831042
Create Date: 2026-08-03 12:41:52.809560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de176a4fd695'
down_revision: Union[str, None] = 'e15d74831042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_participant_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('video_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('participant_identity', sa.String(length=200), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_session_id'], ['video_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_participant_sessions_video_session_id'), 'video_participant_sessions', ['video_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_participant_sessions_video_session_id'), table_name='video_participant_sessions')
    op.drop_table('video_participant_sessions')
    # ### end Alembic commands ###
