"""add crm connections and sync events

Revision ID: e0b348bd8fe6
Revises: 50a378c2734c
Create Date: 2026-08-06 15:25:29.831761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0b348bd8fe6'
down_revision: Union[str, None] = '50a378c2734c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_connections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.Enum('HUBSPOT', 'SALESFORCE', 'PIPEDRIVE', name='crm_provider_enum'), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=False),
    sa.Column('external_account_label', sa.String(length=255), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_connections_account_id'), 'crm_connections', ['account_id'], unique=False)
    op.create_table('crm_sync_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.Enum('CONTACT_SYNC', 'ACTIVITY_SYNC', name='crm_sync_event_type_enum'), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sync_events_account_id'), 'crm_sync_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_crm_sync_events_created_at'), 'crm_sync_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_sync_events_created_at'), table_name='crm_sync_events')
    op.drop_index(op.f('ix_crm_sync_events_account_id'), table_name='crm_sync_events')
    op.drop_table('crm_sync_events')
    op.drop_index(op.f('ix_crm_connections_account_id'), table_name='crm_connections')
    op.drop_table('crm_connections')
    # ### end Alembic commands ###
