"""add jurisdiction to consent_records

Revision ID: e15d74831042
Revises: 34860904d89a
Create Date: 2026-08-03 12:24:07.830538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15d74831042'
down_revision: Union[str, None] = '34860904d89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to GLOBAL (the "applies
    # everywhere" jurisdiction), matching the ORM's Python-side default for
    # new rows - then dropped so it doesn't linger as a DB-level default.
    op.add_column(
        'consent_records',
        sa.Column('jurisdiction', sa.String(length=10), nullable=False, server_default='GLOBAL'),
    )
    op.alter_column('consent_records', 'jurisdiction', server_default=None)
    op.drop_constraint('uq_consent_account_type', 'consent_records', type_='unique')
    op.create_unique_constraint('uq_consent_account_type_jurisdiction', 'consent_records', ['account_id', 'consent_type', 'jurisdiction'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_consent_account_type_jurisdiction', 'consent_records', type_='unique')
    op.create_unique_constraint('uq_consent_account_type', 'consent_records', ['account_id', 'consent_type'])
    op.drop_column('consent_records', 'jurisdiction')
    # ### end Alembic commands ###
