"""add video_sessions and conversation_summaries tables

Revision ID: ea26284f8c8d
Revises: 3f94ba6bd0b7
Create Date: 2026-07-31 14:07:59.198664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea26284f8c8d'
down_revision: Union[str, None] = '3f94ba6bd0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.Enum('VOICEMAIL', 'CALL', name='summary_source_type_enum'), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_account_id'), 'conversation_summaries', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_source_id'), 'conversation_summaries', ['source_id'], unique=False)
    op.create_table('video_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('host_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'ENDED', name='video_session_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_sessions_account_id'), 'video_sessions', ['account_id'], unique=False)
    op.create_index(op.f('ix_video_sessions_host_user_id'), 'video_sessions', ['host_user_id'], unique=False)
    op.create_index(op.f('ix_video_sessions_room_name'), 'video_sessions', ['room_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_sessions_room_name'), table_name='video_sessions')
    op.drop_index(op.f('ix_video_sessions_host_user_id'), table_name='video_sessions')
    op.drop_index(op.f('ix_video_sessions_account_id'), table_name='video_sessions')
    op.drop_table('video_sessions')
    op.drop_index(op.f('ix_conversation_summaries_source_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_account_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
