"""add audit_events and phone_numbers tables

Revision ID: eaba39708baf
Revises: 6471f58b56bc
Create Date: 2026-07-31 10:57:19.772113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaba39708baf'
down_revision: Union[str, None] = '6471f58b56bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_target_id'), 'audit_events', ['target_id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('e164', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_sid', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('RESERVED', 'PURCHASE_PENDING', 'ACTIVE', 'SUSPENDED', 'CANCELLED', name='phone_number_status_enum'), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_sid')
    )
    op.create_index(op.f('ix_phone_numbers_account_id'), 'phone_numbers', ['account_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_e164'), 'phone_numbers', ['e164'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_numbers_e164'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_account_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_audit_events_target_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
